site_name: napari-tissuumaps
site_description: A plugin to add compatibility with Tissuumaps
site_author: Nicolas Pielawski

theme: readthedocs


repo_url: https://github.com/wahlby-lab/napari-tissuumaps

pages:
- Home: index.md
